from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import smtplib
import logging
from app.config import settings
from datetime import datetime
from typing import List, Dict

logger = logging.getLogger(__name__)

class EmailNotifier:
    """SMTP email notification service"""

    def __init__(self):
        self.smtp_server = settings.SMTP_SERVER
        self.smtp_port = settings.SMTP_PORT
        self.sender_email = settings.SMTP_USER
        self.sender_password = settings.SMTP_PASS

    async def send_meeting_summary(
        self,
        email: str,
        meeting_title: str,
        summary: str,
        action_items: List[Dict],
        transcript: List[Dict]
    ) -> Dict:
        """Send formatted email with meeting summary, action items, and transcript"""

        try:
            logger.info(f"Preparing email for {email}")

            # Build action items table HTML
            action_items_html = """
            <table style="width:100%; border-collapse:collapse; margin:20px 0;">
                <tr style="background:#00FF41; color:#000;">
                    <th style="padding:10px; text-align:left; border:1px solid #00FF41;">TASK</th>
                    <th style="padding:10px; text-align:left; border:1px solid #00FF41;">ASSIGNED TO</th>
                    <th style="padding:10px; text-align:left; border:1px solid #00FF41;">DUE DATE</th>
                    <th style="padding:10px; text-align:left; border:1px solid #00FF41;">PRIORITY</th>
                </tr>
            """

            for item in action_items:
                action_items_html += f"""
                <tr style="border:1px solid #00FF41;">
                    <td style="padding:10px; border:1px solid #00FF41;">{item.get('title', 'N/A')}</td>
                    <td style="padding:10px; border:1px solid #00FF41;">{item.get('assigned_to', 'N/A')}</td>
                    <td style="padding:10px; border:1px solid #00FF41;">{item.get('due_date', 'N/A')}</td>
                    <td style="padding:10px; border:1px solid #00FF41; font-weight:bold;">{item.get('priority', 'MEDIUM').upper()}</td>
                </tr>
                """

            action_items_html += "</table>"

            # Build transcript snippet
            transcript_html = ""
            for line in transcript[:20]:  # First 20 lines only
                speaker = line.get('speaker', 'Unknown')
                text = line.get('text', '')
                timestamp = line.get('timestamp', '00:00')
                transcript_html += f"""
                <p style="margin:5px 0; font-size:12px;">
                    <strong>[{timestamp}]</strong> <strong>{speaker}:</strong> {text}
                </p>
                """

            # Build HTML email body
            html_body = f"""
            <html>
                <body style="font-family:'Space Mono', monospace; background:#0A0A0A; color:#00FF41; padding:20px; margin:0;">
                    <div style="border:2px solid #00FF41; padding:20px; background:#131313; max-width:800px; margin:0 auto;">
                        <h1 style="text-shadow: 0 0 8px rgba(0, 255, 65, 0.6); margin-top:0;">[EXEC_ASST_v1] MEETING SUMMARY</h1>

                        <p style="margin:10px 0;"><strong>Meeting:</strong> {meeting_title}</p>
                        <p style="margin:10px 0;"><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>

                        <h2 style="margin-top:30px; text-shadow: 0 0 8px rgba(0, 255, 65, 0.6); color:#00FF41;">EXECUTIVE SUMMARY</h2>
                        <p style="border-left:4px solid #00FF41; padding-left:15px; background:#000; padding:15px; line-height:1.6;">
                            {summary}
                        </p>

                        <h2 style="margin-top:30px; text-shadow: 0 0 8px rgba(0, 255, 65, 0.6); color:#00FF41;">ACTION ITEMS ({len(action_items)})</h2>
                        {action_items_html}

                        <h2 style="margin-top:30px; text-shadow: 0 0 8px rgba(0, 255, 65, 0.6); color:#00FF41;">TRANSCRIPT EXCERPT</h2>
                        <div style="background:#000; padding:15px; border:1px solid #00FF41; max-height:400px; overflow-y:auto; font-size:11px;">
                            {transcript_html}
                        </div>

                        <p style="margin-top:30px; font-size:10px; color:#00FF41/50; text-align:center;">
                            Generated by EXEC_ASST_v1 | Meeting Assistant
                        </p>
                    </div>
                </body>
            </html>
            """

            # Send email
            msg = MIMEMultipart()
            msg["From"] = self.sender_email
            msg["To"] = email
            msg["Subject"] = f"[EXEC_ASST] {meeting_title} Summary"
            msg.attach(MIMEText(html_body, "html"))

            logger.info(f"Connecting to SMTP server {self.smtp_server}:{self.smtp_port}")

            with smtplib.SMTP_SSL(self.smtp_server, self.smtp_port) as server:
                server.login(self.sender_email, self.sender_password)
                server.send_message(msg)

            logger.info(f"Email sent successfully to {email}")
            return {"success": True, "message": f"Email sent to {email}"}

        except Exception as e:
            logger.error(f"Email sending error: {str(e)}")
            return {"success": False, "message": f"Failed to send email: {str(e)}"}
